---
- hosts: load_balancer
  sudo: yes
  tasks:
    - name: update openssl
      yum: 
        name: openssl
        state: latest
    - name: Add EPEL YUM repository
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    - name: install wget, unzip
      yum:
        name: wget, unzip
    - name: Install pip packages
      yum: 
        name: libselinux-python, bc, python-pip 
        state: present
        disable_gpg_check: true
    - name: Download Consul template x64
      get_url: url=https://releases.hashicorp.com/consul-template/0.19.4/consul-template_0.19.4_linux_amd64.zip dest=/tmp/consul-template.zip
    - name: unzip consul-template
      shell: unzip /tmp/consul-template.zip -d /tmp
    - name: move consul to /usr/bin
      shell: mv /tmp/consul-template /usr/bin
    - name: Add the user 'consul'
      user:
        name: consul
        state: present
        password: 123456
    - name: create folder etc/consul.d
      file:
        path: /etc/consul-template
        state: directory
        owner: consul
        group: consul
        mode: 0755
    - name: Enabled 5000 port
      firewalld:
        port: 5000/tcp
        permanent: yes
        state: enabled
    - name: Restart the firewalld service to load in the firewall changes
      service: 
        name: firewalld 
        state: restarted
    - name: create folder etc/haproxy
      file:
        path: /etc/haproxy
        state: directory
        owner: consul
        group: consul
        mode: 0755
    - name: Copy haproxy.tpl file
      copy:
        src: ../templates/config_files/haproxy.tpl
        dest: /etc/consul-template/haproxy.tpl
        owner: consul
        group: consul
        mode: 0755
    - name: Copy server service
      template:
        src: ../templates/config_files/serviceLoadBalancer.service
        dest: /etc/systemd/system/serviceLoadBalancer.service
        owner: consul
        group: consul
        mode: 0755
    - name: Start the service consul server
      service:
        name: serviceLoadBalancer
        state: started
        enabled: yes